# Structure

## Even more general structure

1. Introduction
2. Domain
3. Methods
4. Analysis

## General Structure

1. Introduction
	- General Summary of entire thesis
2. Domain
	- Intro: 
	- Energy mix is important!
		- Fed by global demands
		- Severe consequences to fossil fuel dependency
			- Local:
				- air ([Beijing](https://www.theguardian.com/world/2016/feb/22/beijing-raises-red-alert-threshold-for-air-pollution-warning)) and groundwater ([Parker County, Texas](http://europe.newsweek.com/fracking-wells-tainting-drinking-water-texas-and-pennsylvania-study-finds-270735?rm=eu)) pollution
				- [oil spills](https://en.wikipedia.org/wiki/List_of_oil_spills)
				- [destabilization of regions rich in fossil fuels](https://www.theguardian.com/commentisfree/2015/dec/08/oil-fuels-war-terrorists-isis-climate-movement-peace-cop-21)
			- Global:
				- [Rising Sea Levels](http://www.nytimes.com/interactive/2015/12/02/world/The-Marshall-Islands-Are-Disappearing.html)
				- [Crop Failure](http://www.dphu.org/uploads/attachements/books/books_2078_0.pdf)
				- [Ocean acidification](http://science.sciencemag.org/content/320/5882/1490)
				- [The carbon bubble](http://www.theguardian.com/news/2015/apr/08/can-world-economy-survive-without-fossil-fuels)
		- Continued global demand for the next century
			- Mainly in electricity
			- Demand from the developing world
		- *Segway:* Alternative energy production which is based on renewable resources is the key to reducing these socio-economic and ecological consequences. 
			- An increasing number of alternatives are being developed. 
			- Solar, Wind, Tidal, Geothermal, Fusion.
			- [Along with Wind, Solar appears to be the most likely to become viable alternatives in the next decade.](http://www.iea.org/publications/freepublications/publication/technology-roadmap-solar-photovoltaic-energy---2014-edition.html)
		- The contribution of solar energy to global energy supplies is not limited by resource availability
	- Solar Industry
		- ["The amount of solar radiation intercepted by the earth is more than three orders of magnitude higher than global annual use"](http://www.undp.org/content/dam/aplaws/publication/en/publications/environment-energy/www-ee-library/sustainable-energy/world-energy-assessment-energy-and-the-challenge-of-sustainability/World%20Energy%20Assessment-2000.pdf)
		- Rather these factors are key:	
		- The availability of low cost technologies to convert solar to electricity or hydrogen
		- of effective energy storage technology
		- high efficiency end use technologies <!-- see above ref 163 -->
		- Central to these factors in continued technological innovation. 
			- [Better energy absorbing technologies that make use of innovative nano-materials continue to evolve.](http://europe.newsweek.com/indoor-solar-cells-made-possible-moth-eye-graphene-breakthrough-430827)
		- Costs associated with photovoltaic power continue to drop, from [$4 a watt in 2008 to $0.80 in 2014](http://www.forbes.com/sites/paulrodgers/2014/09/30/the-rise-of-solar/)
		- Part of that drop is improvements in technology which are able to capture an increasing amount of photovoltaic radiation.
		- Yet, much of the success of solar energy production thus far has been driven by a favorable regulatory environment and government subsidies.
			- Technology improves, but is still below the threshold of self-reliance
		- The economic viability of photovoltaic projects is still questionable, as solar companies do go bankrupt. 
			- Note big bankruptcies. [SunEdison](http://www.reuters.com/article/us-sunedison-inc-bankruptcy-idUSKCN0XI1TC)
		- There are other ways to optimize yields and boost the profitability of solar companies than improvements underlying technology.
		- Reliability is a big challenge in the photovoltaic area. 
			- Insert metrics about failure
		- Predictive maintenance is one solution to the reliability problem.
		
	- Predictive Maintenance, a critical element in optimizing the industry
		- What is predictive maintenance, formal definition
			- Mobley - "Uses actual operating conditions to optimize plant performance"
				- "Predictive maintenance is a condition-driven preventive maintenance program"
				- predictive maintenance uses direct monitoring of the mechanical condition, system efficiency, and other indicators to determine the actual mean-time-to-failure or loss of efficiency for each machine-train and system in the plant. 
				- Where does it sit in the wider maintenance tasks
		<!-- - Historical evolution of predictive maintenance. (Maybe, or is the intro enough) -->
		- What does it offer?
			- Empowerment of maintenance regimes. Optimized outputs, lower replacement costs. Being able to plan against operational hazards rather than being at their mercy. 
		- Use cases
			- fault identification
			- near-term failure probability
			- Residual lifetime estimation 
		- Requirements for a predictive maintenance process:
			- Implement a corrective mode of action
				- Without the ability to act, no amount of relevant information will be of value. The obvious fact should be stressed that predictive maintenance, in and of itself, does not extend the lifetime of operational systems, only maintenance actions do\cite{Levitt2011}.
			- Data of sufficient quality
				- Abundant
					- More is better, repeated observations
				- Historical
					- The more historical, the better
				- Balanced
					- The more failure observations, the better
				- Relevant 
					- to the use-case (target of prediction)
					- Domain knowledge to select subset of relevant data
				- Noiseless
					- Measurement error, missing values and other forms of noise.
					- 
			- Typical data sources\cite{Uz2016}
				- System Attributes
					- make, model, 
					- date of installation
					- static data
				- System Conditions and Usage
					- time-varying features that capture the aging pattern of the system
					- telemetry from various sensors installed within the system directly related to the conditions of that system
					- ideally should capture degrading trend leading up to the actual failure event
					- temporal data
					- granularity
				- Maintenance History
					- dates and times for maintenance activities
					- logs of maintenance activities
						- what activities were performed
						- what components may have been repaired or replaced
						- absence can cause misleading results
					- inferring maintenance downtime from sensor logs is not an acceptable recourse
				- Failure history
					- dates and times for failure events
					- including the nature of the failure, the failure mode
					- very important that it is done in a timely fashion
			- Temporal data vs static data
			- (maybe) Feature engineering
	- Photovoltaic Inverter Context
		- What is a photovoltaic power station?
		- Introduce the various components.
			- PV modules
			- Balance of System Components
		- Demonstrate this industry doesn't quite meet the requirements for such a system, good old edge cases.
		- Smaller quantities of accurate temporal data (except energy output)
		- Abundance of static data
		- Exogenous temporal data, (like weather) but not at the same unit of analysis, usually quite noisy.
	- Data Generation 
		- Introduce data structure, variables, what they are meant to represent.
		- Show how the context steers the choice of variables.
		- Aim to give a realistic (not pessimistic) level of data found at today's photovoltaic plants
	- Justification of Modeling Choice
		- Numerous ways to tackle this kind of problem.
		- Given the context:
			- Choose to focus on Bayesian time-to-event analysis.
			- Estimate residual lifetime of an inverter
			- Foundation: accurately predict the remaining lifetime of the device by explaining as much of the variation within the data as possible.
		- Ideal in cases of small quantities of time-dependent data
3. Methodology
	- Reliability Analysis
		- Basic Functions
			- $T \rightarrow t$ 
			- CDF, PDF
			- Survival -> Hazard Function
			- Hazard -> Cumulative Hazard
			- Return from Cumulative Hazard back to PDF
			- Time shifted functions
			- Residual Lifetime
		- Common Distributions
			- Exponential
			- Gompertz
			- Weibull
			- Gamma
	- Censoring and Truncation
		- Define Truncation
		- Define Censoring
		- Define difference
		- Define mathematical construction of right-censoring
		- Type I, Type II and Random Censoring
		- Mathematical Construction
	- Multiplicative Hazard Model
		- Note about Proportional Hazards Models
		- Time-Dependent Covariates
		- Time-Varying Effects
		- Frailty & Hierarchical Model
	- Estimation (HMC and Gibbs)
		- Bayesian Approach
			- Likelihood Function
		- Metropolis Algorithm
			- Random walk through parameter space
				- Favoring steps that have relatively high posterior probability
				- Propose a jump, jump sampled randomly from current position
					- Move if jump is a higher posterior probability than current position
					- Otherwise move probabilistically, ratio of probabilities
		- Proposal distribution must be symmetric centered around the current position
			- Usually multivariate Gaussian
			- Inefficient, especially in the tails of the distribution
			- Fixed shape causes inefficiencies
4. Analysis
	- Briefly: Explicitly state the goal of predictive maintenance again.
		- Create system that enables maintenance processes to be directed to inverters with greatest potential for failure.
			- Formal: Determine the inverters with the largest hazards in next instantaneous period
	- Data management and Feature Engineering
		- Doing a lot with a little
		- The data comes in parts but that is not the format that is required for the model
		- We talked about the data sources in the first chapter, here are examples of what those data sources will look like in raw form
		- Here is how they can/should be collapsed into a workable data set that is the quadruple $(Y_i, d_i, X_i, Z_i)$
		- Averages across periods to diminish volatility, vs raw data
		- Counts of binary variables over time
		- Time dependent covariates are just interval censored
		- Signals Processing is out of scope
		- Testing the resulting covariates is more important than their logical construction, use what works!
			- Encode subject matter expertise into covariates, statistics is **not itself** the answer
	- Data Generation Redux - Now with Numbers
		- N = 500, 5 Parks, uneven number of inverters at parks
$$ T = H_0^{-1}\left [\frac{-\ln(U)}{w_{ij} \exp(\boldsymbol\beta^T \textbf{x}_{ij})}  \right ] $$
		- Weibull Version
$$ T = \left [\frac{-\ln(U)}{w_{ij}\lambda \exp(\boldsymbol\beta^T \textbf{x}_{ij})}  \right ]^{1/\nu} $$
		- Big Table
			- Define Failure Mode (Failure is requires replacement)
				- Infant Mortality
				- Old Age Mortality
			- Define each category $w_{ij}$
				- Park - Big $\sigma^2$
				- Inverter Type - Small $\sigma^2$
			- Define each covariate, $\textbf{x}_{ij}$
				- Days of operation
				- Standardized Electrical Output - $\mathcal{N}(0,1)$
				- Maintenance Logs
					- Count of repairs
					- Days since last repair
					- Count of replacement
					- Days since last replacement part
				- Park Level Data
					- Standardized Avg Temperature
					- Standardized Humidity
					- Interaction effect between low avg temp and low humidity
	- Stan and a medium for model fitting
		- Introduce Stan
			- Successor to BUGS and JAGS
			- Give BRIEF introduction to the components
				- Data
				- Parameters
				- Model
				- Derived Quantities
				- Functions (Recent)
			- Model construction
				- Define hazard functions
				- Allow Stan to take care of the rest
	- Predictive performance and model comparison
		- Ideal case
			- Model residual lifetime
			- Concordance between prediction and failure
			- It is highly like that it this is not the metric to evaluate the model by, due to censoring will always pose challenges
		- Compromise Case
			- Highest hazard in next instantaneous period
			- Some indication of the urgency of the first instance of failure
		- Evaluating Model Performance
			- Deviance-based methods, WAIC
			- Hazards of cross validation in sequence learning
				- Weaker cross validation that retains sequences. 
			- Unbalanced data issues (99% not failed)
	- Fit Model
		- Present output
5. Extensions (Optional)
	- Improved Baseline Hazard Estimation (Gaussian / Dirchlet Process)
	- Competing Risk for repeated failure events
6. Conclusion




