# Introduction

<!-- 
0. Acknowledgments
0.5 Intended Audience
1. Introduction
	- General Summary of entire thesis

## Introduction Notes 
 - You hate writing introductions, but you still have to, and it still has to catch the attention of your audience and communicate clearly the priorities of the thesis. It doesn't have to be as thick as you think it does though. 
 - Make sure to clearly provide a structure for the remaining document. 
 - There is no need to justify any of the choices, do that within the text.
 - Event-history analysis vs signal processing

Stick in structure of remaining text

 -->

# Acknowledgments

No man is an island.

While a single name appears on the cover of this document, it should not be implied that anything was, or could be done alone. Everyone is the product of their environments and I've had the esteemed privilege to be assisted and inspired by many wonderful people. 

So my great appreciation to Ewa Podkolinska, Jerzy Podkolinski, Alina Kroeker, Raymond Kroeker, Tom Ruette, Wannes Meert, Mathias Verbeke, Gregory Schiano, Jan Aerts, Gerda Glaskens, Luc De Raedt, Roel Braekers, Geert Verbeke, Eric Schmitt, Rui Barbosa, Stijn Van Weezel, Akshat Dwivedi, Irzam Hardiansyah, Zhu Meng, Sytze Elzinga, Justin Fischedick and most importantly Rianne Hartemink.

Thank you, all of you. May you enjoy reading this as much as I enjoyed writing it.

- Richard Podkolinski
	- Den Haag, The Netherlands, 2016


# Intended Audience

Good academic literature is the kind that is capable of taking a complex topic making it accessible to a broader audience. In an effort to adhere to that standard, the intended audience of this thesis is not a pure mathematician, rather a general practitioner in the area of predictive maintenance or reliability analysis. Emphasized is the development of understanding and intuition for the underlying models and how to handle edge cases. 

However, a certain degree of mathematical development is required to understand this text. Recommended is an understanding of the calculus of probabilities at the level of Blitzstein and Huang\cite{Blitzstein2014} as well as a first course on Bayesian linear models at the level of McElreath\cite{McElreath2016}. 

To ensure access to rigorous results, an extensive list of references and resources are made available at the end of each chapter, dubbed "Extended Reading". These resources elucidate many of the technical aspects of the modeling process and mathematical foundations which are beyond the scope of this text.

<!-- 
Maybe include something about the change of voice between the first and second half of the thesis.
- In chapter 2 I am explaining the state of the world, it's declarative
- In chapter 3, I am exploring the mechanics of a mathematical system with you, it's meant to be interactive.


 -->

## Introduction

Maintenance is not sexy, but it is essential. It is the immune system of the modern industrialized world. Without it, the myriad of systems we depend on for safeguarding our collectively quality of life would rapidly deteriorate and disappear. Yet, few sing the praises of the multitude of technicians and engineers which are responsible for ensuring trains run on time, computer systems remain accessible or that bridges do not suddenly collapse. Paradoxically, this lack of visibility is a testament to the uninterrupted success of these activities. 

The preceding decades have brought with them rapid innovation in the area of maintenance. What has historically been a manual and labor-intensive activity is increasingly becoming a scientific process, one that leverages technology to optimize operations. Modernization has meant going beyond traditional methods of maintenance based on reactions to failure or scheduled inspection and moving towards those that utilize data and predict failure. Such a trend can have a widespread impact on operational expenses. Reactive methods generally incur greater costs due to downtime and a need for more expensive replacement parts. Scheduled inspections share similar pitfalls, requiring downtime, specialized machinery and also running the risk of inadvertent damage to the objects they seek to maintain. Predictive maintenance minimizes many of these drawbacks. Judgments about the state of a device are made as a result of continuous monitoring of actual operating conditions\cite{Mobley2002}. This reduces downtime and allows for a better allocation of maintenance resources. Most importantly, predictive maintenance enables faults to become apparent *before* failure allowing for contingencies, such as repair or replacement, to ensure constant output.


The transition toward predictive maintenance owes much to the continued development of sensor technology. More reliable, accurate, and most importantly, inexpensive sensors have enabled continuous monitoring in a wider range of domains. Many modern devices come with built-in sensors that record output or other context-specific data that can be used to assess health. Increasingly, many also include connectivity that allows telemetry to be retrieved remotely on demand. This reality is likely what has spurred widespread innovation in the field, with more than half of the publications on predictive maintenance emerging within the last decade. <!-- Limo Search = 703 / 989 | Google Scholar = 3300 / 5450 --> Unfortunately, this data gluttony has also led to a form of tunnel vision, with the majority of this work dedicated to enabling predictive maintenance exclusively in informationally rich contexts. As a result, authors are predominantly preoccupied with domains where data is high dimensional, time-dependent, with fine granularity and encoded without error. 


While the future may make these ideal circumstances ubiquitous, there is still a wide set of domains where this is not a reality. Sensors may have become increasingly cheap and plentiful but they can still be expensive in absolute terms. The majority of the sensors included in new products are meant to extend functionality and the continuous monitoring they enable is an fortunate but inadvertent consequence. Yet, for many devices the inclusion of additional sensors means an increase in manufacturing costs, which is often prohibitive. No product developer of sound mind would argue for the inclusion of a sensors in a t-shirt to prevent stitching failure. The sensors would vastly increase the final cost of the original product. However, this kind of cost-benefit dilemma is found throughout numerous domains where the sensor costs are higher than the manufacturing cost of the product. In these domains, data is rarely high dimensional, time-dependent, fine and encoded without error. Despite these limitations, there is still a need for predictive maintenance. 

<!-- Make this explicit, you want the reader to know what to expect from the next chapters in the text. -->

This thesis will address the development of a predictive maintenance system in informationally sparse domains. In so doing, it will attempt to fill the void in the current literature on predictive maintenance in domains where limited access to operational data is the norm. It will attack the problem from the perspective of Bayesian time-to-event analysis, a statistical modeling approach which is used to estimate the remaining lifetime of an object.

The following chapters encompass the development of this strategy. 

The first chapter examines predictive maintenance and introduces an example domain meant to provide a business case for the further analysis. The solar industry with its heavy reliance on dwindling government subsidies and firm need to reduce costs prove an ideal domain for such systems. Further, the photovoltaic inverter, a device with limited output found at every solar power plant is a highly relevant object of study. 

The second chapter considers methodology, providing the probabilistic and statistical foundations required to understand Bayesian time-to-event analysis. These foundations are then used to introduce more complex models centered around the Accelerated Failure Time model with shared Frailties. Additionally, estimation procedures for these models using Hamiltonian Monte Carlo in the probabilistic programming language Stan are examined. 

The third chapter covers the analytical process using simulated photovoltaic inverter data. It makes use of a series of data scenarios which represent states of informational sparsity. In so doing, it illuminates the various considerations that have to be taken into account when working with limited operational data using the previously developed statistical models. 

Finally, we conclude with a general summary of the material. 


<!-- Optional, so be clear this might not get done -->
<!-- The fourth and final chapter deals with extensions that improve the model either because more data is has become available or  -->




