# Predictive Maintenance


<!-- 

The first chapter examines predictive maintenance and introduces an example domain meant to provide a business case for the further analysis. The solar industry with its heavy reliance on dwindling government subsidies and firm need to reduce costs prove an ideal domain for such systems. Further, the photovoltaic inverter, a device with limited output found at every solar power plant is a highly relevant object of study.


# Predictive Maintenance
	- What is? Details.

Central motivation:
- maintenance tasks are costly
- repair and replacement leads to downtime and decreased output 



-->

As it seems impossible to actually write something about this general obviousness of a chapter. So let's try some free writing. What is this chapter about? It is meant to serve as a general introduction to predictive maintenance. To do this, we require an understanding of maintenance in general, which has historically been a labor intensive, largely reactive, crisis-mode endeavor. It always went somewhere between, grease the machine every once in a while, to oh god, it's on fire, let's do something about it. Generally unpleasant, difficult and uninspired work, but a fundamental requirement of running any industrialized operation. The problem is these industrial operations are super inefficient. This is where maintenance steps in. Even in its simplest forms, checking if something is properly lubricated. 



What does predictive maintenance promise? It promises to put an end to the reactivity that is generally associated with ensuring an industrial device functions.

In the broadest sense, predictive maintenance seeks to answer several questions. 
- Will this machine break? Probably, if not, see cure models
- When will this machine fail?
- From what did the machine fail?


OUTLINE THIS CHAPTER 

1. Catchy Intro






When will a machine fail? It seems like an innocuous enough question, but within it are hidden all the ambiguities of the modern scientific process.




To be clear there are multiple methods to address the challenge that predictive maintenance presents. We will be approaching this from one direction which is meant to address the issues from our selected domain. This does not, however, preclude other domains with other needs that may require different predictive maintenance strategies to accomplish. 




<!-- Introduce and define Maintenance  -->
Predictive maintenance has long been a goal in reliability analysis. As its name suggests, predictive maintenance refers to a set of processes designed to determine the condition of operational equipment in order to determine when maintenance should be performed. <!-- CITEHERE --> In other words, it is a set of tools to predict when an industrial device may require support to keep it operational. 

Underlying this definition is the practicality that maintenance is a substantial business expense for many organizations. The knowledge of how to correctly allocate maintenance resources ensures optimal operation as well as reducing costs and downtime. 




<!-- 
Contextualize predictive maintenance in the framework of general maintenance strategies.
- Subset of preventative maintenance
- Versus corrective maintenance and replacement
 -->

Predictive maintenance is a sub process in the broader field. 
Run-to-failure management

*Feature Engineering: Doing a lot with a little*


<!-- 
- Considerations for how deal with data recording, what to record and why?
	- Failure autopsy, sensors or maintenance testing
	- Continuous monitoring (economically impractical)
	- Hazards of lab testing leading to accelerated failure

- Define a Failure Mode
	- State why it is important for Failure Modes to be separated
	- Use of competing risk models when multiple failure methods occur.
	- Fit one model per failure mode
		- May ignore the dependency among failure modes
-->

Evolution of maintenance

Reactive > Scheduled > Predictive

 - Reactivity: Don't fix it until it's broke
 - Scheduling: Check if it is about to break periodically
 - Predictive: Continuous monitoring to estimate failure time

Maintenance has historically been a labor intensive activity. The task can be roughly broken down in the following steps: Stop the machine, inspect the machine with any number of tools



The central motivation being that these tasks incur costs and thus should only 
The idea being that maintenance as a task incurs costs, and such processes can be used to only perform the task when it is required. 

It has historically been a manual and labor intensive activity. Assuming maintenance is even done at all, it has long-since been subject to the same general pattern. 


## Mobley 2002 - Introduction to Preventative Maintenance Quotes and Notes:

"Analysis of maintenance costs has shown that repairs made in a reactive (i.e., after failure) mode are normally three times greater than the same repairs made on a scheduled basis." - Mobley, p.4


"The common premise of predictive maintenance is that regular monitoring of the actual mechanical condition, operating efficiency, and other indicators of the operating condition of machine-trains and process systems will provide the data required to ensure the maximum interval between repairs and minimize the number and cost of unscheduled outages created by machine-train failures" p.4

"It is the means of improving productivity, product quality, and overall effectiveness of manufacturing and production plants." p.5

"Condition Monitoring. Statistics and probability theory are the basis for condition- monitoring maintenance. Trend detection through data analysis often rewards the analyst with insight into the causes of failure and preventive actions that will help avoid future failures. For example, stadium lights burn out within a narrow period. If 10 percent of the lights have burned out, it may be accurately assumed that the rest will fail soon and should, most effectively, be replaced as a group rather than individually." p.47

"Scheduled. Scheduled, fixed-interval preventive maintenance tasks should generally be used only if failures that cannot be detected in advance can be reduced, or if dictated by production requirements. The distinction should be drawn between fixed-interval maintenance and fixed-interval inspection that may detect a threshold condition and initiate condition-monitoring tasks. Examples of fixed-interval tasks include 3,000-mile oil changes and 48,000-mile spark plug changes on a car, whether it needs the changes or not. This may be wasteful because all equipment and their operating environments are not alike. What is right for one situation may not be right for another." p.47

