# Domain

<!-- 

OLD OUTLINE, KEEP FOR POSTERITY, INTEGRATE THEN DELETE

3. Domain Knowledge - Photovoltaic Inverter
	- Low information, limited economic resources
	- High reliability problem

- Describe the state of the industry as still subsidy-fueled, and why predictive maintenance is needed. 
- Describe a basic photovoltaic system
- Describe why the situation is different for photovoltaic plants compared to other energy sources. e.g. Information sparcity.
- Describe the failure mechanism a.k.a. The failure mode
	- Note that infant mortality is not part of the failure mode
	- Early failures are considered right censored at the time of failure
	- Potentially resolved through either two different models, one for early failure and mode failure, or some form of mixture model.
- Describe the explanatory variables
	- Manufacturer
	- Site
	- Location
	- Noisy Alarm
	- Qty of Lab Tests
- Failure Mode for Photovoltaic Inverter
	- [Reliability the weak link in the solar industry](http://www.interpv.net/tech/tech_view.asp?idx=49&part_code=030190059&page=2)
 -->

- Intro
- Energy Mix
- Solar Industry
- Predictive Maintenance
- Photovoltaic Inverter
- Data Generation
- Model Choice

This chapter **yadda yadda ...**



## Solar Industry

Altering the global energy mix is essential to the future evolution of our civilization and possibly our survival as a species. Currently, the global energy mix is dominated by fossil fuels. Approximately, 82% of global energy consumption remains the product of coal, natural gas and petroleum\cite{EIAOutlook2016}. A century of heavy reliance on these non-renewable fossil fuels as the central source of energy has had severe ecological and socio-economic consequences. Locally, there have been countless instances of environmental damage, such as air\cite{Tatlow2016} and groundwater\cite{Schlanger2014} contamination and oil spills\cite{OilSpills2015}. Additionally, regions rich in fossil fuels are destabilized as wealthy nations seek to guarantee future supply\cite{Solnit2015}. Globally, the prospect of catastrophic climate change looms large, with implications including rising sea levels\cite{Davenport2015}, ocean acidification\cite{Feely2008}, crop failure\cite{Parry2004} and the economic devastation of a bursting carbon bubble\cite{Carrington2013}. 

Despite these persistent consequences, a reduction in consumption is highly unlikely. Global energy demand is projected to increase rapidly in the coming decades. As of  2012, global demand was estimated at $5.8\cdot 10^{20}$ Joules and is expected to rise by 48% to $8.6\cdot 10^{20}$ by 2040\cite{EIAOutlook2016}. The majority of this increase is the product of higher demand for electricity, which will increase by 70% before 2040. The majority of this new demand, roughly 87%, is expected to come from countries in the developing world\cite{OECD2015}. Due to their economic conditions, these countries will undoubtedly utilize whichever energy source is cheapest, regardless of the consequences. 

In this context, alternative energy production, sourced from renewable resources, is required to evade a future of socio-economic instability and ecological collapse. Fortunately, an increasing number of alternatives are being developed with the support of governments. Solar, wind, tidal, geothermal and fusion have all seen major investments over the past decade. In 2015 alone, renewable power capacity received twice the investment compared to new projects based on fossil fuels\cite{FrankfurtSchool2016}. Of these projects, wind and solar appear the most likely to become viable within the next decade\cite{OECD2014}. 

The contribution of solar energy is particularly attractive as its supplies are not limited by resource availability. At least for the next five billion years, solar energy is expected to reach the earth without interruption. Furthermore, the amount of solar radiation intercepted by the earth is several orders of magnitude higher than global energy consumption\cite{Goldemberg2000}. Given such potential, it is not surprising that the rate of installations of solar systems has increased exponentially in the past decade\cite{EPIA2014}. 

The central drivers of this growth have been continued technological development and innovative government policy. In terms of technological development, three major factors contribute to growth. First, the continued improvement of efficiency of end-use technologies. This ensures that electrical output is utilized optimally by the time it reach consumers\cite{Wilson2012}. Second, the reduction in cost and enhancement of energy storage technologies\cite{IRENA2015}. This ability is particularly important for the solar energy industry as production fluctuates based upon the availability of sunlight. Finally, and most importantly, the reduction of costs associated with technologies that convert solar energy into electricity.

In terms of reducing costs and optimizing production, the advances continue. There are regular invention of novel materials which enable broader capture of solar radiation\cite{Shi2015}. As well as developments that optimize power processing systems, ensuring that energy produced can be efficiently transfered back to the power grid\cite{Weckx2014}. These technological improvements have led to a substantial decrease in the costs associated with photovoltaic power. The average weighted utility-scale solar photovoltaic installation cost has more than halved in the last five years\cite{IRENA2016}.

However, further cost reductions are needed. The central bottleneck for greater expansion of solar power continues to be economic self-sustainability. In most markets, solar is not yet able to compete with other forms of energy generation without  government policy incentives\cite{OECD2011}. These usually come in the form of subsidies or feed-in tariffs that provide solar companies with long-term contracts for energy above market value. These are meant to provide stability as well as offset the cost of further technological development\cite{Couture2010}. However, these subsidies are reduced incrementally by design, as they are meant to serve as a temporary incentive to promote cost-saving innovation. As the subsidies are reduced, the industry is more subject to market forces and more reliant on its own ability to optimize its efficiency. The current low price of oil and coal, coupled with fickle government support for renewable energy\cite{FrankfurtSchool2016} present a difficult status quo\cite{Hals2016}. 

While technological innovation is likely to continue to reduce costs, there are avenues for further optimization given the current infrastructure. Among them are improvements in reliability, specifically in photovoltaic systems. Reliability has been a long-standing challenge\cite{Petrone2008} and a particularly important one given systems long payback periods\cite{NEEDED}. Innovation in components and manufacturing are methods for addressing reliability, but other more immediate options exist. Among them, optimized maintenance activities have the potential to dramatically reduce costs. Yet, these optimizations require accurate predictions about the state of component health. To do this, predictive maintenance is required.

## Predictive Maintenance

Predictive maintenance is generally defined as the process of using direct monitoring of conditions, efficiency and other indicators to determine the health and likelihood of failure of a system. These results indicate when maintenance tasks should be performed\cite{Mobley2002}. Informally, predictive maintenance is an activity geared toward indicating the degree of wear of a piece of equipment and predicting its useful life\cite{Levitt2011}. In doing so, it empowers organizations with the ability to plan and act against operational hazards. This additional time allows for corrective actions to be prepared including the ordering of parts and materials, often at lower prices, coordinating labor and scheduling downtime. In turn, this allows the business, not the environment, to dictate when service interruptions occur. 

<!-- 
Check the introduction, see if the evolution of predictive maintenance described there needs to be expanded, do so if you think that is right, maybe use a gray box 

Something along the lines of:
> The rapid evolution of predictive maintenance owes much to the rapid expansion of network connectivity in most consumer products. 
> A few things have, one is the fact that they no longer stop production to inspect, because they have better data capture technologies
> The other is that as a result of those data capture technologies, shorter intervals of monitoring are possible
> So you won't run a big vibrational test every 3 months, rather you'll have a vibration sensor sending out data hourly
> predictive maintenance activities were limited by the availability of data. Vibrational analysis, thermography, fluid analysis and electrical monitoring.
-->

All predictive maintenance processes attempt to address one or more of the following three generic use cases\cite{Uz2016}. First, is fault identification. Accurately identifying the source of failure of a particular system is essential to developing effective corrective countermeasures. Second, is near-term failure probability. This permits immediate operational risks to be addressed and avoided. Third, and finally, is estimation of residual lifetime. This allows both short and long-term operational risks to be taken into account. All the cases are overlap and should not be treated as mutually exclusive. Yet, each requires slightly different considerations, methodology and inputs when developing a predictive maintenance process.

The preconditions for the development of a predictive maintenance process differ depending on the domain and selected use cases. Yet, there is a common core of needs including the ability to implement results, high data quality and a typical set of maintenance related sources. 

The ability implement a corrective mode of action is universal requirement. Without the ability to act, no amount of information derived from a predictive model will be of any value. After all, predictive maintenance does not, in and of itself, improve the reliability of operational systems, only maintenance activities do\cite{Levitt2011}. 

As predictive maintenance depends on condition monitoring, data sources of a suitable quality are required. Ideally, data sources should be historical, abundant, balanced, relevant and noiseless. Models that generate predictions about the future require historical data from which to derive patterns about operating conditions. The more historical information is recorded, the greater the opportunity of the model to observe the system along its lifetime. This in turn results in more accurate predictions about future health. Furthermore, the more abundant the data sources the better. As a greater number of repeated observations provides a greater certainty about the state of a system at any given time. Yet, in this context, historicity is of greater importance than abundance. It is possible to be tracking a large quantity of systems, but only for a short period of time. This would be inadequate due to a natural imbalance in the data for this type of process. Even in systems with profoundly poor reliability, healthy observations will greatly outnumber failures. Without a greater quantity of historical data, failures are even less likely to be present in the data. Therefore, a degree of balance is required in the data between the number of observed failures and healthy observations. Additionally, data sources must be relevant to the task. Data sources should be taken advantage of which offer the greatest potential for predictive power. Domain knowledge from subject matter experts should be exploited to provide a contextually appropriate selection. These experts should also implement mechanisms that ensure data sources are as free as possible from measurement error, missing values and other forms of noise. While unavoidable in a practical setting, noise can undercut the reliability of models and introduce a greater degree of uncertainty in predictions. 

<!-- 
Potentially Insert!
- Abundance can offset the effect of some types of noisy observations. 
--> 

<!-- Better Segway needed -->

A typical set of data sources for a predictive maintenance process includes system attributes and conditions, maintenance logs and failure history\cite{Uz2016}. 

Attributes are a set of static values that define the identity of the system. This includes elements such as a system's ID, model number, date of installation, location, a list of components as well as any other technical specifications that might be relevant to its reliability. As these attributes are unlikely to change over time, they provide context which allows for the comparison of systems with one another. 

Conversely, conditions are temporal values that define the state of a system at specific points in time. These values are captured through telemetry from sensors or other periodic observations. They can include, but are not limited to, component status, system yields, environmental conditions or any other time-varying data directly related to system reliability. These conditions are meant to capture the evolution of the system as it ages and provide the degradation pattern leading up to failure. 

Maintenance history logs contain all service interactions with any particular system. These time stamped logs should contain any inspections, identify suspicious or replaced components and provide a listing of any corrective activities that maintenance teams performed. This data is crucial in providing context for the health of any system over time. It not only allows for the determination of the efficacy of maintenance tasks but also improves the ability better understand the sequence of events leading up to a system breakdown.

Finally, failure history includes the time and conditions of observed breakdowns across systems. These values are usually entered manually upon system failure. An accurate and timely declaration that a machine has failed and the cause of that failure is central to the task of predictive maintenance. A generic recording of failure, without determining the cause, is not sufficient. Utmost care must be taken to ensure that the failure history records are current and complete. Delays in recording failure times detrimentally impact predictive performance. This is likely the single most important data source for a predictive maintenance process. If recorded inaccurately, it will undo the entire endeavor. 

<!-- 
**granularity**
You need to insert somewhere the issue of data granularity, specifically the length of the interval between repeated measures. 
 -->

<!-- 
Segway needed.
-->



### Predictive Maintenance in Photovoltaic Inverters

As stated earlier, predictive maintenance presents an opportunity for improved cost optimization in the solar industry. This section examines one area of application within the solar industry, namely predictive maintenance of photovoltaic inverters. First, a general picture of a typical photovoltaic system at the utility-scale is given, demonstrating the role of inverter reliability in its operation. Second, a description of the considerations are given when developing a predictive maintenance process in this domain. 

<!-- 
Maybe insert:
https://en.wikipedia.org/wiki/File:From_a_solar_cell_to_a_PV_system.svg 
-->

A photovoltaic system is composed of two main elements, one is a what is typically described as a solar panel and the other are balance-of-system components. 

A solar panel is usually composed of individual photovoltaic cells wired in series, called a string. This is done to increase the voltage produced by individual cells. The strings are then wired in parallel to increase the current. This collection of strings is then encapsulated in a weather-resistant housing and is what we typically refer to as a solar panel. These panels are then connected to one another to form a solar array. The connection can be done in either series or in parallel depending on the desired voltage or current of the system. 

Balance-of-system (BOS) components encompass everything that is not the solar panels or array. The BOS components include the array structure, solar tracker, connectors, AC and DC wiring, overcurrent protections, disconnects, interconnects, charge and system controllers, maximum power point trackers, batteries, inverters and any other accessories. The purpose of the BOS components is to integrate the solar system into the utility grid.

A photovoltaic inverter is an electrical device that converts the variable DC output of the solar panels to an AC frequency allowing it to be fed to the utility grid. Of all the BOS components, the inverter has historically had the  most reliability problems. A international decade long survery of photovoltaic systems indicated that a majority of failures (65%) were attributed to inverters\cite{Laukamp2002}. The same research also stated there appears to be ongoing reliability improvements, as the rate of failure declined over time. Even with these improvements, recent research confirmed that inverters continued to be the most likely causes of photovoltaic system failure\cite{Golnas2013}. 

Inverter reliability is essential for ensuring steady output of a solar system. When an inverter fails, it disables all photovoltaic cells upstream of it. This makes it the single largest source of productivity loss in a solar system. It is for this reason, a predictive maintenance process focused on the photovoltaic inverter can serve as a valuable mechanism for optimizing operational outputs. 

Yet, there are a number of difficulties in deploying such a process within this domain. Given its role as the device connecting the solar panels to the utility grid, the inverter contains most of the intelligence in a photovoltaic system\cite{Golnas2013}. However, this intelligence is minor and narrowly focused. At any given moment, an inverter records its electrical output in kilowatt hours (kWh) and possibly provides an error code if a malfunction has been detected\cite{SMA2012}. Unfortunately, these error codes are noisy and are not always present prior to an inverter failure. Even when an error code is present, it does not uniquely define a specific cause of failure. It, instead, expresses a symptom of failure, such as current leakage, over-voltage or software error, rather than the underlying cause. Furthermore, there is a tacit acknowledgment of the lack of causality between the presence of these error codes and inverter failure. This can be seen in most dashboards of solar systems which will report a count of the number of error codes that have occurred throughout the day. Thus, a single error is not seen as particularly severe and, as stated earlier, may not even occur prior to inverter failure. 

The lack of robust system condition data poses a challenge in developing a predictive maintenance process. At its core, the lack of condition data stems from the modularity of design in photovoltaic systems. Every additional component not directly related to generating electrical output is viewed as an operational overhead, requiring cost-benefit justifications which often do not fit into profitability planning. As a result, the inclusion of accurate sensors which track reliability indicators like temperature and humidity at the inverter level are viewed as cost prohibitive additions and generally not included. This leads to informational sparsity in photovoltaic systems and especially in inverters. 

This can be contrasted with another alternative energy source, wind, which by design does not face such problems. A wind-turbine has roughly a hundred sensors that measure everything including ambient humidity, temperature, airflow and electrical current\cite{NEEDED}. Of course, wind-turbines are self-contained and far less modular compared to a photovoltaic system. However, other industries, such as cloud computing, that have similar modular designs do not share the same sensor deficiencies. For example, the average cloud storage server rack contains more than a hundred temperature sensors, with each server averaging three\cite{NEEDED}. The key is that the monitoring requirement of a cloud computing server rack and a solar system are comparable. Yet, there is a substantial difference in the application of sensors to create a cohesive picture of health for each unit. The cloud storage industry clearly believing that system conditioning data is worth the overhead expense. 

As the industry matures and solar power becomes independently profitable, it is likely that it too will invest more heavily in condition-based monitoring of photovoltaic inverters. However, this is not yet the case. Most sensors in a solar system are at the scale of solar park as a whole, not at the scale of an inverter. Thus, temperature, humidity and solar radiance data, assuming they are recorded at all, are provided by park level sensors. With large solar parks having multiple sensors installed. This is remarkably suboptimal, as solar parks at a utility-scale can encompass a large landmass, some exceeding a hundred square kilometers. A dozen sensors scattered among that landmass will undoubtedly produce a noisy signal regarding the health of any individual inverter. There are also attempts to reduce costs of sensors by employing satellite sensor data. However, this provides even worse resolution than park level sensor data and thus even noisier signals regarding the health of an inverter.

While the system itself may not record a substantial amount of useful data, the humans working with the systems do. This provides contextual information which can be used in the construction of a predictive maintenance system. System attributes are almost always kept complete and up to date. The make, model, installation date and location of inverters are recorded. The quality of this data has much to do with contracts that utility-scale solar companies have with manufacturers. This often includes offers to replace faulty units within a specific time of purchase. Maintenance logs are also usually kept with detailed entries providing the source of 


	- maintenance logs are usually complete
	- failure history is not always complete


Then transition to data generation.

Set the scene of not an idealized data set rather one that should be a reality within several years as the industry matures. 



Types of Inverters
- String
- Central
- Micro

- Physically nearby failure as an indicator.

\cite{Golnas2013}
The string inverters show a failure rate that is one order of magnitude lower compared with the most reliable central in- verters. While microinverters are not shown here, the available evidence shows a ticket/inverter-year ratio which is 3–4 times lower than that for the string inverters.\cite{Golnas2013}

While there have been numerous studies about the long-term reliabilityofPVmodules,similarstudiesforinvertersareharder to find. The assumption for inverter failures is that they will follow the “bathtub curve” where a relatively high number of infant mortality failures appear in the early life of inverters,to be followed by a low rate of stochastic failures during the bulk of their useful life and by a higher rate of wear-induced, end-of-life failures.

\cite{Golnas2013}
However, as the inverter contains most of the intelligence of
a PV system, its failures are also easier to capture.Subsystems upstream of the inverter are rarely monitored at a resolution that would allow a direct report of a malfunction. It is important to note that communication failures are on par with inverter- related issues in terms of frequency, but they are not counted along with the rest of the failures because they are transient and do not impact production.

\cite{Golnas2013}
However, the limited capability for deep failure analysis may dampen the value of the collected information.

DC side of the system is distributed, so failures are more likely to 


\cite{Dhere2005}
"Kim et  al  have  suggested  a  PV  system  with  suppression functions  so  as to limit power disturbances such as variation of voltage and frequency and harmonic voltage generation into utility  [24].  The power disturbances are caused  by  unstable output pattems due to variability of weather and customer  load  in a highdensity grid connection"

- Islanding
- partial shadowing of PV arrays




We now return our attention to the solar industry and introduce predictive maintenance in the context of a photovoltaic system.

Mean  Time  Between  Failures  (MTBF)  of approximately  50  years has been predicted by a theoretical analysis  of  an inverter not exposed  to excessive temperature  [  131.  However, the shockingly different field experience from older systems has shown that the inverter is the most vulnerable component in PV systems and lost  15%  of tbe PV power. Reliability Data at  FSEC  includes information on  103 grid-connected PV systems that used  176  inverters  [31]. The  FSEC  database includes systems using PV arrays from  9  manufacturers and inverters from  4  manufacturers. During  1999-2003,  213  events have been recorded on these  103  systems, of which  139  events i.e.  65%  were attributed to inverters. Most inverter events  were  attributed to  poor maximum power-tracking function and ability to maintain grid connection. They required software upgrades  or  replacementlrepair  of  inverter by the manufacturer. Approximately  6  inverter failures were due to  lightning strikes at or near the PV arrays.  Most  events were recorded during the first year  of  system operation. Many of the inverters that had frequent failures  are  no longer available on the market.  A  fair number of system reliability events were due to  BOS.  They included tripping of  dc breakers and failure of source circuit overcurrent devices, as well as ac overcurrent devices, requiring manual resets  or  replacement of components  [31].


Petrone

The field experience has shown that the inverter is the most vulnerable component [5], [11]–[14], [26]. Fig. 1 puts into evidence that investment in a new inverter is required three to five times over the life of a PV system [101]


\cite{Laukamp2002}
	- The information given from owners does not always distinguish between a temporary malfunction, (which automatically resets) and a failure, i.e. a defect requiring a repair. Even less a malfunction can be distinguished from an inverter shut down due to irregular grid conditions. Data for figure 3 include all such effects. Considering true hardware reliability of the inverter, these data are conservative.
	- Inverter problems as the major source of energy loss



----

For Justification of the Model

Richard, [28.06.16 02:14]
The irony is that what I'm doing is actually somewhere between two and three

Richard, [28.06.16 02:14]
because given my limited access to data (which is a precondition of this thesis), you're never going to get accurate predictions on residual lifetimes

Richard, [28.06.16 02:15]
so I am compromising, I'm interested in concordance of the population of lifetimes rather than accurate estimating each individual lifetime


Predictive maintenance improves reliability by detecting deteriorations earlier than it could be by manual means. 







-----

----


For utility-scale systems, hardware still makes up the majority of the cost per watt\cite{Chung2015}. Replacing components

- Replacement components
- Operational downtime

At their core, all these activities require reliable 

At its core, this optimization requires prediction




----








Inverters with 3G connectivity to allow for constant monitoring of outputs





Fortunately, an increasing number of cleaner alternatives are being developed. 

Causes of failure
- Difference in failure mode based on string or micro-inverters.
	- String inverters
		- Voltage Stress
		- Small caps fail due to QC issues
	- Single failure in micro-inverters only eliminates one panel, while a string inverter results in a series of panels going offline.
- Excessive temperatures
		- Requires inverter level data, weather is not enough
- Surge voltage from the grid
- Electrolytic -> Capacitor Plague
- Lightening strikes
- Water condensation
- Lack of robust software by certain manufacturers
- ESD damage on inverters

Superior reliability of smaller form factors




I mean I can state that there is a shortage of skilled maintenance people in the field, (even now) which might play a role in the cost perception of maintenance activities.

<!-- 
This thesis will focus on a data-centric approach to improving the current state of solar systems, namely data-driven maintenance.


 -->


----
<!-- 
Data of Sufficient Quality

Abundant
- The more the better
Historical
- Observe as much of the lifetime of a system as possible.
- For example, even if we have a million devices being observed, if they are only observed for a short period of time, it will be difficult to generate accurate predictions about the device's end of life. 
Diverse
- Data should provide as many observations as possible for the different states of the machine. Normal operating conditions are more likely to be observed. The conditions leading up to failure are required and will almost certainly be the minority of observations.
Relevant
- Data should be relevant to the use case under study. The
Noiseless
- The more data the better. A greater quantity of data implies a greater number of observation of the system in different conditions, reducing overall uncertainty. Ideally, we would prefer this data lack measurement error, missing values or other forms of noise.

 -->