# Domain

<!-- 

OLD OUTLINE, KEEP FOR POSTERITY, INTEGRATE THEN DELETE

3. Domain Knowledge - Photovoltaic Inverter
	- Low information, limited economic resources
	- High reliability problem

- Describe the state of the industry as still subsidy-fueled, and why predictive maintenance is needed. 
- Describe a basic photovoltaic system
- Describe why the situation is different for photovoltaic plants compared to other energy sources. e.g. Information sparcity.
- Describe the failure mechanism a.k.a. The failure mode
	- Note that infant mortality is not part of the failure mode
	- Early failures are considered right censored at the time of failure
	- Potentially resolved through either two different models, one for early failure and mode failure, or some form of mixture model.
- Describe the explanatory variables
	- Manufacturer
	- Site
	- Location
	- Noisy Alarm
	- Qty of Lab Tests
- Failure Mode for Photovoltaic Inverter
	- [Reliability the weak link in the solar industry](http://www.interpv.net/tech/tech_view.asp?idx=49&part_code=030190059&page=2)
 -->

- Intro
- Energy Mix
- Solar Industry
- Predictive Maintenance
- Photovoltaic Inverter
- Data Generation
- Model Choice

This chapter **yadda yadda ...**



## Solar Industry

Altering the global energy mix is essential to the future evolution of our civilization and possibly our survival as a species. Currently, the global energy mix is dominated by fossil fuels. Approximately, 82% of global energy consumption remains the product of coal, natural gas and petroleum\cite{EIAOutlook2016}. A century of heavy reliance on these non-renewable fossil fuels as the central source of energy has had severe ecological and socio-economic consequences. Locally, there have been countless instances of environmental damage, such as oil spills\cite{OilSpills2015}, air\cite{Tatlow2016} and groundwater\cite{Schlanger2014} contamination. Additionally, regions rich in fossil fuels are destabilized as wealthy nations seek to guarantee future supply\cite{Solnit2015}. Globally, the prospect of catastrophic climate change looms large, with implications including rising sea levels\cite{Davenport2015}, ocean acidification\cite{Feely2008}, crop failure\cite{Parry2004} and the economic devastation of a bursting carbon bubble\cite{Carrington2013}. 

Despite these persistent consequences, a reduction in consumption is highly unlikely. Global energy demand is projected to increase rapidly in the coming decades. As of  2012, global demand was estimated at $5.8\cdot 10^{20}$ Joules and is expected to rise by 48% to $8.6\cdot 10^{20}$ by 2040\cite{EIAOutlook2016}. The majority of this increase is the product of higher demand for electricity, which will increase by 70% before 2040. The majority of this new demand, roughly 87%, is expected to come from countries in the developing world\cite{OECD2015}. Due to their economic conditions, these countries will undoubtedly utilize whichever energy source is cheapest, regardless of the consequences. <!-- something something consequences better segway needed -->

In this context, alternative energy production, sourced from renewable resources, is required to evade a future of socio-economic instability and ecological collapse. Fortunately, an increasing number of alternatives are being developed with the support of governments. Solar, wind, tidal, geothermal and fusion have all seen major investments over the past decade. In 2015 alone, renewable power capacity received twice the investment as compared to new projects based on fossil fuels\cite{FrankfurtSchool2016}. 

These investments 

These investments allow for these projects to increasingly compete with fossil fuels. 

Along with wind, solar appears to be the most likely to become an economically viable alternative to fossil fuels in the next decade. 

> What are you trying to say? I am trying to state that alternative energy is necessary to preventing a future of socio-economic instability and ecological collapse. But that is too harsh!


Alternative energy production, sourced from renewable resources, coupled with a decarbonization of electrical production, is crucial to reducing the aforementioned consequences. 

Fortunately, an increasing number of cleaner alternatives are being developed. 



