# Methods
```
4. Methods
	- Reliability Analysis
	- Censoring
	- Accelerated Failure Time Model
	- Frailty & Hierarchical Model
	- Estimation (HMC and Gibbs)
	- Model Selection
@TODO: Do not build here, build in separate files
```



Proportional Hazards models seek to find a shift in the hazard rate for an individual at every age of *t*. 


- Distribution Choice
  - Weibull
  - ?Lognormal
  - ?Loglogistic 


- Stratification == Frailty
  - Traditional regression methods would presume a shared fixed effect for the shape or scale of the distribution.


- Considerations for how deal with data recording, what to record and why?
	- Failure autopsy, sensors or maintenance testing
	- Continuous monitoring (economically impractical)

- The type of estimation done on the baseline hazard has implications for future forecasting. Non-parametric models lack the ability to forecast future failure rates beyond the last failure time.

# Notes

 - "Whereas OLS produces a predicted dependent variable (fitted value) for each individual; Cox regression produces a *probability distribution for the duration of each individual's waiting time*" 
 - "Whereas in OLS a change in the estimated parameter's value implies a linear change in every individual's fitted value; in Cox regression a change in an estimated parameter implies *a proportional shift in each individual's hazard rate* **at all ages**"
	- [Cite](http://courses.demog.berkeley.edu/mason213F15/)