# Censoring and Truncation

Censoring and Truncation is a common facet of time-to-event analysis. It is so common that it is often mis-represented as being unique to time-to-event analysis.**REFHERE** Yet, censoring and truncation occur in any environment where measurements may be omitted or inaccurately recorded. The phenomenon occurs in something as simple as a weight scale with a maximum beyond which it records the same value. 

The reason why censoring and truncation is ubiquitous in time-to-event analysis is by construction. As time is the central unit, analysis often inquires about events that have not occurred, which automatically leads to issues of truncation and censoring. We are often unable or unwilling to wait long enough to see all events occur, such as failure, and have complete information. Therefore, we must infer from the information available which requires a mechanism to accommodate those times which are not yet fully observed. 

- Define Censoring
	- Provide Example
- Define Truncation
	- Provide Example
- Contrast Censoring and Truncation
- Set independence assumptions between censoring, truncation and failure time distributions
- Provide example within the current photovoltaic domain.
	- Types of censoring
		- Random
		- Type I, due to multiple inverters coming online at the same time.
- Provide Mathematical construction of both.
	- Change in likelihood function
- References and Further Reading

The level of information available when measurements are handled determine the type of 

In mathematical terms, censoring and truncation requires the estimation of two additional distributions to handle the missing or omitted data. We do this through the construction of a binary variable 







## Additional Notes

- Censoring is missing with a known direction compared to Truncation which is omission
- One of the unique aspects of time-to-event analysis is that data does not always contain an observation of the event in question. 
- Though really it is the lack of normally distributed errors. 
- Data in this case should be right censored.
	- It may also be left-truncated, though that can be avoided with careful data management.

- While truncation does not feature explicitly in our case-study, it should be noted that it can appear due to poor data entry practices. Systems administrators should be careful to avoid truncation in their data inadvertantly. For example, if a device is dead on arrival, it is easy to simply omit it from the records rather than take the time to input a failure at t = 0. However, the omission of such records induces truncation, which biases the estimation of the underlying survival functions. 

- Heavy Truncation -> Estimation Problems


- May provide how one works correctly with right censored or truncated distributions.
  [Parameterization and Bayesian Modeling](http://www.stat.columbia.edu/~gelman/research/published/parameterization.pdf)

## Older Text


The solution is to create a binary random variable ( $\delta_i$) to account for whether a failure is observed and a random variable ($Y_i$) which combines our observation of the time with whether that failure is observed.

Let $T$ denote the lifetime of a device and $C$ a random censor time. Every device has a lifetime $T_i$ and a censor time $C_i$ and for every device we observe a pair ($Y_i, \delta_i$) where:

$$  Y_i = \min(T_i,C_i) \qquad \text{ and } \qquad \delta_i = \left\{\begin{matrix} 1 \text{ if } T_i \le C_i\\ 0 \text{ if } C_i < T_i \end{matrix}\right.$$

% Likelihood estimation
