---
title: "Distractions"
author: "Richard Podkolinski"
date: "May 27, 2016"
output: html_document
---

# [Opening sublime through the cygwin terminal](http://twincreations.co.uk/launch-sublime-text-from-cygwin-terminal/)
Tags = [sublime, cygwin]

```
vi /usr/local/bin/subl
```

Then insert:
```
#!/bin/sh
/cygdrive/c/Program\ Files/Sublime\ Text\ 3/sublime_text.exe $1 &
```

Finally
```
chmod +x /usr/local/bin/subl
```

Sublime can then be started with:
```
subl .
```

# [Launch SumatraPDF from cygwin](https://cygwin.com/ml/cygwin/2005-06/msg00336.html)
Tags = [cygwin, pdf, sumatrapdf]

```
vi /usr/local/bin/spdf
```

Then insert:
```
#!/bin/sh
cygstart /cygdrive/c/Program\ Files/SumatraPDF/SumatraPDF.exe -reuse-instance "$(cygpath -aw "$1")" 
```

This doesn't actually work due to the suffix feeding in the cygwin address not the windows address.
So instead of 
R:\operations\markdown_cheatsheet.pdf
it goes to:
R:\cygdrive\r\operations\markdown_cheatsheet.pdf

Finally
```
chmod +x /usr/local/bin/spdf
```

Sublime can then be started with:
```
spdf .
```



# [Open Path in Sublime Text](http://stackoverflow.com/questions/19410938/sublime-text-open-containing-folder)
Tags = [sublime, path]

Go to Preferences -> Key Bindings User, and insert the following:
```
	{ "keys": ["ctrl+alt+e"], "command": "open_dir", "args": {"dir": "$file_path", "file": "$file_name"} }
```

# [Sublime Text Keyboard Shortcuts](http://docs.sublimetext.info/en/latest/reference/keyboard_shortcuts_win.html)
Tags = [sublime, keyboard]

CTRL+` 			<- Opens Control Panel

CTRL+SHIFT+P 	<- Command Pallet (for installing packages among other things)



# [Sublime R Interface](https://github.com/christophsax/SublimeStudio)
Tags = [sublime, R]

CTRL+SHIFT+M = Knits file

# Ouput html and PDF files from Sublime

This requires the following packages:

- [MikTeX](http://miktex.org/howto/install-miktex)
- [Pandoc](https://github.com/jgm/pandoc/releases/tag/1.17.0.2)


# [Markdown Formatting inline in Sublime](https://github.com/jonschlinkert/sublime-monokai-extended)
Tags = [sublime, markdown, syntax]


# [Changing Font Face of Sublime Text](https://www.sublimetext.com/docs/3/font.html)
Tags = [sublime, font]

Preferences -> Settings - User, then paste the following:

```
	"font_face": "InputMonoNarrow",
	"font_size": 13
```



# [Sublime Package Manager Install](https://packagecontrol.io/installation)
Tags = [sublime, setup]

Install Packages with CTRL+SHIFT+P


# [Reverting Sublime Text to Defaults](http://www.sublimetext.com/docs/2/revert.html)
Tags = [sublime, setup, reset]

To avoid keybinding error

# Open Cygwin in Folder
Tags = [windows, cygwin, shortcut, folder]

Add AHK entry:
```
#r::
run C:\cygwin\bin\mintty /bin/sh -lc 'cd "$(cygpath "/cygdrive/r/0000_Code/Hermes/")"; exec bash'
return
```

# AHK Script for code blocks in Sublime
Tags = [ahk, clipboard, markdown]

WIN+` <- Keyboard Shortcut

```
#`::
	Send ^c
	ClipWait 2
	SendInput, ``````
	SendInput, {Enter}
	SendInput, ``````
	SendInput, {Home}{Enter}{Up}
	SendInput, Send^v
return
```

# [AHK Syntax for Sublime Text](https://github.com/ahkscript/SublimeAutoHotkey)
Tags = [sublime, ahk, syntax]

# [AHK for Opening Cygwin Terminal in a Specific Folder](http://superuser.com/questions/592086/how-to-open-a-cygwin-shell-at-a-specific-directory-from-netbeans)
Tags = [ahk, cygwin, folder]
```
#r::
run C:\cygwin\bin\mintty /bin/sh -lc 'cd "$(cygpath "/cygdrive/r/0000_Code/Hermes/")"; exec bash'
return
```

# [Distraction Free Writing Settings](https://www.sublimetext.com/docs/3/distraction_free.html)
Tags = [sublime]

Preferences -> Settings - More -> Distraction Free Settings

```
{
	"line_numbers": false,
	"gutter": false,
	"draw_centered": true,
	"wrap_width": 80,
	"word_wrap": true,
	"scroll_past_end": true,
	"font_face": "InputMonoNarrow",
	"font_size": 15,
}
```

# [Books every programmer should read](http://stackoverflow.com/questions/1711/what-is-the-single-most-influential-book-every-programmer-should-read/)
Tags = [books, programming]

 - [In the beginning there was command line](http://cristal.inria.fr/~weis/info/commandline.html)
 - [The Tao of Programming](http://www.mit.edu/~xela/tao.html)

 
# AHK Open current terminal or start a new one
Tags = [ahk]

Change the terminal button to open the current terminal if the terminal is already open, otherwise open it.

```{ahk}
#r::
IfWinExist, ahk_class mintty 
{
	WinActivate, ahk_class mintty
	return
} else {
	run C:\cygwin\bin\mintty /bin/sh -lc 'cd "$(cygpath "/cygdrive/r/0000_Code/Hermes/")"; exec bash'
	WinActivate, ahk_class mintty
	return
}
return
```

# AHK Sublime Mouse Open Switch
Tags = [ahk, sublime]

Fixes the CTRL+Tab issue in Sublime

```
; Sublime Text 
#IfWinActive, ahk_class PX_WINDOW_CLASS
F24::
SendInput ^{PgDn}
return
F23::
SendInput ^{PgUp}
return
```

# Spell checking in Sublime Distraction Free Mode
Tags = [sublime]

Preferences -> Settings - More -> Distraction Free

```
"spell_check": true,
"dictionary": "Packages/Language - English/en_US.dic",
```

# Markdown Preview in Sublime
Tags = [sublime, markdown]

CTRL+SHIFT+P -> Install Packages -> Markdown Preview

Then in Preferences -> Key-Bindings -> User

```
 { "keys": ["alt+m"], "command": "markdown_preview", "args": {"target": "browser", "parser":"markdown"} }
```

To get it to handle mathjax support.

Preferences -> Package Settings -> Markdown Preview -> User

```
"enable_mathjax": true,
```


# [Atom Text Editor](https://atom.io/beta)
Tags = [software]

# Wrap with Math Tags
Tags = [autohotkey, markdown]

```
#w::
SendInput, ^x
ClipWait 2
SendInput, $^v$
return
```

